name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MLFLOW_TRACKING_URI: file://$(pwd)/mlruns
  MODEL_NAME: hybrid-recommender

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repo
      - uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy joblib

      # Run MLflow Project
      - name: Run mlflow project
        run: mlflow run MLProject --env-manager=local


      # Get Latest Run ID
      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/* | head -1 | xargs -n1 basename)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      # Build Docker Image from Model
      - name: Build Docker Image
        run: |
          echo "Using run_id: $RUN_ID"
          mlflow models build-docker --model-uri "mlruns/0/$RUN_ID/artifacts/model" --name $MODEL_NAME

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag $MODEL_NAME ${{ secrets.DOCKERHUB_USERNAME }}/$MODEL_NAME:latest

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$MODEL_NAME:latest
