name: CI/CD MLflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up MLflow dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLProject/requirements.txt
          pip install mlflow[extras] scikit-learn joblib

      - name: Run Modelling Script
        working-directory: MLProject
        run: python modelling.py

      - name: Upload artifact (model)
        uses: actions/upload-artifact@v4
        with:
          name: svd-best-model
          path: MLProject/model_artifacts/model.pkl

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image with MLflow
        run: |
          cd MLProject
          mlflow models build-docker --model-uri ./model --name alifinaaulia/mlflow-ci-recommender

      - name: Push Docker Image to Docker Hub
        run: docker push alifinaaulia/mlflow-ci-recommender
